name: "UEC textbooks app CI workflow"
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test_flutter_app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.x'
          channel: 'stable'
      - name: "Run Flutter CI Workflow"
        uses: ./.github/actions/flutter_test
