name: "UEC textbooks app CI workflow"
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test_flutter_app:
    runs-on: ubuntu-latest
    container:
      image: cirrusci/flutter:3.3.10
    steps:
      - uses: actions/checkout@v3
      - name: "Run Flutter CI Workflow"
        uses: ./.github/actions/flutter_test
